leopardslab/CrawlerX

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTORS.md
=> Adding template files to the project

crawlerx_app/package-lock.json, crawlerx_app/package.json, crawlerx_app/src/router/index.js, crawlerx_app/src/views/Login.vue, crawlerx_app/src/views/SignUp.vue
=> Update home path as dashboard

scrapy_app/scrapy_app/spiders/crawlerx.py, scrapy_app/scrapy_app/spiders/wikipedia.py
=> Add wikipedia spider for the scrapy_app

scrapy_app/rabbitmq_broker/rabbitmq_consumer.py, scrapy_app/scrapy_app/pipelines.py, scrapy_app/scrapy_app/settings.py, scrapy_app/scrapy_app/spiders/crawlerx.py
=> Add MongoDB connection pipeline for the scrapy spiders

scrapy_app/scrapy_app/spiders/stackoverflow.py
=> Add spider for StackOverflow

crawlerx_app/package.json, crawlerx_app/src/components/Contents/Dashboard.vue, crawlerx_app/src/components/Contents/Projects.vue, crawlerx_app/src/main.js, crawlerx_app/src/router/index.js, crawlerx_app/src/views/Dashboard.vue
=> Adding dashboard samples sketches of creating projects and jobs

README.md
=> Adding README.md file to the project

crawlerx_app/package.json, crawlerx_app/src/main.js, crawlerx_app/src/views/Dashboard.vue
=> Add axios REST calls to connect with Django APIs

crawlerx_server/main/clients/firebase_auth.py, crawlerx_server/main/services/project.py
=> Add firebase authentication to check valid user(temp)

scrapy_app/scrapy_app/pipelines.py, scrapy_app/scrapy_app/settings.py, scrapy_app/scrapy_app/spiders/crawlerx.py
=> Index crawled data in ElasticSearch

crawlerx_app/package.json, crawlerx_app/src/components/Contents/Dashboard.vue, crawlerx_app/src/main.js, crawlerx_app/src/router/index.js, crawlerx_app/src/views/Dashboard.vue
=> Add dynamic contents for job details in Dashboard view

crawlerx_server/crawlerx_server/settings.py, crawlerx_server/main/services/crawl_job.py, crawlerx_server/main/services/project.py, crawlerx_server/main/services/scrapy.py, scrapy_app/rabbitmq_broker/rabbitmq_consumer.py, scrapy_app/scrapy_app/pipelines.py, scrapy_app/scrapy_app/spiders/crawlerx.py
=> Adding job name for the schema

crawlerx_app/src/components/Contents/Dashboard.vue, crawlerx_app/src/router/index.js, crawlerx_app/src/views/Dashboard.vue
=> Load data from the MongoDB database by calling to Django server

crawlerx_server/crawlerx_server/urls.py, crawlerx_server/main/clients/elasticsearch_connection.py, crawlerx_server/main/clients/mongo_connection.py, crawlerx_server/main/services/crawl_job.py, crawlerx_server/main/services/elasticsearch.py, crawlerx_server/main/services/project.py, crawlerx_server/main/services/scrapy.py, scrapy_app/scrapy_app/pipelines.py
=> Adding service backend APIs for Django

crawlerx_app/package.json, crawlerx_app/src/components/Contents/Dashboard.vue, crawlerx_app/src/components/Contents/ELKAnalysis.vue, crawlerx_app/src/components/Contents/JobData.vue, crawlerx_app/src/components/Contents/Jobs.vue, crawlerx_app/src/components/Contents/Projects.vue, crawlerx_app/src/main.js, crawlerx_app/src/router/bus.js, crawlerx_app/src/router/index.js, crawlerx_app/src/views/Dashboard.vue
=> Adding ELK Anslysis, job and project wise breakdown UIs to the dashboard

crawlerx_app/src/views/Dashboard.vue
=> Adding file upload and job scheduling features

crawlerx_server/main/services/crawl_job.py, crawlerx_server/main/services/project.py, scrapy_app/rabbitmq_broker/rabbitmq_consumer.py, scrapy_app/scrapy_app/settings.py
=> Adding crawl job scheduling feature with python scheduler

README.md
Update readme with elasticsearch server
=> Update readme with elasticsearch server

README.md
$subject by adding how to setup in container based environment details. 
Relates: https://github.com/leopardslab/CrawlerX/pull/55
=> Update readme file 

crawlerx_app/package.json, crawlerx_app/src/components/Contents/JobData.vue, crawlerx_app/src/main.js
Updated the json viewer
- Users can  now select which data they want copy to the clipboard
- Add some colors to json viewer
- User can collapsed brackets and see the length 
- Add toaster notifications wen user copy something into clipboard 
#39
=> Add Improvent to the JSON viewer

crawlerx_app/src/views/Login.vue
I have added forgot password functionality with the UI.
#63 
Now users can reset their password without thehelp of firebase console
=> Add forgot password functionality

crawlerx_app/package.json
=> Add missing vue-json-pretty package

crawlerx_app/.env, crawlerx_app/package-lock.json, crawlerx_app/package.json, crawlerx_app/src/main.js
Refactor .env file to load in all cases
=> Refactor env file to load in all cases

README.md, crawlerx_app/README.md
=> Update readme files

scrapy_app/scrapy_app/spiders/reddit.py
Adding new scrapy spider for Reddit URLs
=> Add Reddit URL crawling spider

crawlerx_app/src/views/Dashboard.vue
Adding reddit spider to the crawler dropdown. This PR is relates to the PR https://github.com/leopardslab/CrawlerX/pull/79 which adds the reddit spider to the Scrapy app
=> Adding reddit spider to the crawler dropdown

crawlerx_app/src/views/Dashboard.vue, scrapy_app/scrapy_app/spider_common.py, scrapy_app/scrapy_app/spiders/github_trending.py
Adding github_trending spider to scrapy app and web app
Relates to: https://github.com/leopardslab/CrawlerX/issues/41
=> Adding github_trending spider to scrapy app

crawlerx_helm/templates/backend/configmap.yaml, crawlerx_helm/templates/backend/deployment.yaml, crawlerx_helm/templates/backend/service.yaml, crawlerx_helm/values.yaml
Adding Django backend server Helm chars. This PR adds the following
- Deployment artifact
- Service artifact
- ConfigMap 
https://github.com/leopardslab/CrawlerX/issues/94
=> Adding Django backend server helm artifacts

crawlerx_helm/templates/scrapy_app/configmap.yaml, crawlerx_helm/templates/scrapy_app/deployment.yaml, crawlerx_helm/templates/scrapy_app/service.yaml, crawlerx_helm/values.yaml
Adding Scrapy app backend server Helm chars. This PR adds the following
- Deployment artifact
- Service artifact
- ConfigMap 
https://github.com/leopardslab/CrawlerX/issues/95
=> Adding scrapy app server helm artifacts

.gitignore, airflow_docker/docker-compose.yaml, airflow_docker/logs/scheduler/latest
Adding Apache airflow  server composer file. 
https://github.com/leopardslab/CrawlerX/issues/102
=> Adding airflow docker-composer for future reference

crawlerx_helm/requirements.yaml, crawlerx_helm/values.yaml
Adding MongoDB and RabbitMQ broker Helm chars. This PR adds the following
- Dependency file as requirements.yaml
- Default custom values in values.yaml
https://github.com/leopardslab/CrawlerX/issues/96
=> adding rabbitmq and mongodb helm dependencies

crawlerx_helm/requirements.yaml, crawlerx_helm/templates/backend/celery_beat_deployment.yaml, crawlerx_helm/templates/backend/celery_worker_deployment.yaml, crawlerx_helm/templates/backend/configmap.yaml, crawlerx_helm/templates/backend/django_deployment.yaml, crawlerx_helm/templates/scrapy_app/configmap.yaml, crawlerx_helm/templates/scrapy_app/deployment.yaml, crawlerx_helm/templates/web_app/configmap.yaml, crawlerx_helm/templates/web_app/deployment.yaml, crawlerx_helm/values.yaml
=> Adding configmaps and template values for the CrawlerX Helm deployment

crawlerx_helm/README.md
=> Adding initial helm documentation

crawlerx_helm/README.md
=> Refactoring helm documentation

crawlerx_helm/README.md
=> Adding parameters and configurations of helm deployment

crawlerx_helm/templates/NOTES.txt
=> Updating notes.txt file

crawlerx_helm/README.md
=> Updating helm readmefile with helm resources

crawlerx_app/src/views/Dashboard.vue
=> tor_onion option as new spider
